### ISSUE TITLE
ValueError:

### ISSUE THREAD

**Issue by mishugeb** [broadinstitute/SignatureAnalyzer-GPU#12]
Hi,
I am trying to run the example code  -
python SignatureAnalyzer-GPU.py --data example_data/POLEMSI_counts_matrix.txt --max_iter=100000 --output_dir SA_EXAMPLE --prior_on_W L1 --prior_on_H L2 --labeled

Unfortunately, I am getting the following  value error:
**Traceback (most recent call last):
  File "SignatureAnalyzer-GPU.py", line 1, in <module>
    import pandas as pd
  File "/home/ubuntu/anaconda3/envs/SA/lib/python3.7/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/ubuntu/anaconda3/envs/SA/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "__init__.pxd", line 872, in init pandas._libs.tslib
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216**

Could you please help me to solve the problem?
Thanks

**The environment specs are listed below:
# packages in environment at /home/ubuntu/anaconda3/envs/SA:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
cudatoolkit               9.0                  h13b8566_0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
freetype                  2.9.1                h8a8886c_1  
imageio                   2.6.1                    pypi_0    pypi
intel-openmp              2020.0                      166  
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
matplotlib                3.1.3                    pypi_0    pypi
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.14.3                   pypi_0    pypi
olefile                   0.46                     py37_0  
openssl                   1.1.1d               h7b6447c_4  
pandas                    0.23.0                   pypi_0    pypi
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1  
pyarrow                   0.11.1                   pypi_0    pypi
pycparser                 2.19                     py37_0  
pyparsing                 2.4.6                    pypi_0    pypi
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.1.0           py3.7_cuda9.0.176_cudnn7.5.1_0    pytorch
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
scikit-image              0.16.2                   pypi_0    pypi
scikit-learn              0.22.1                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                45.2.0                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torchvision               0.3.0           py37_cu9.0.176_1    pytorch
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0**

**Comment by shankara-a** [comment]
This seems to be a problem with the numpy version you have - try updating it!

https://stackoverflow.com/questions/53904157/numpy-ufunc-has-the-wrong-size-try-recompiling-even-with-the-latest-pandas-and

**Comment by mishugeb** [comment]
Thanks, it worked.
