### ISSUE TITLE
importin NMF_Functions

### ISSUE THREAD

**Issue by rvangara** [broadinstitute/SignatureAnalyzer-GPU#17]
Hi
1. I changed Line 14 of ARD_NMF.py - `from .NMF_functions import *` to `import NMF_functions` as the former version is throwing an error.

2. While running the example line `python SignatureAnalyzer-GPU.py --data example_data/POLEMSI_counts_matrix.txt --max_iter=100000 --output_dir POLEMSI_EXAMPLE --prior_on_W L1 --prior_on_H L2 --labeled`

 it is throwing an error `NameError: name 'NMF_algorithim' is not defined`. I couldn't find relevant parameters in help. Can you please let me know what is the parameter that's missing or the change caused this issue?

**Comment by shankara-a** [comment]
Hi - please see this repo for the stable SignatureAnalyzer package: https://github.com/getzlab/getzlab-SignatureAnalyzer. We will take a look at what's going on here!

**Comment by rvangara** [comment]
Okay Thanks!
