### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by sqsun** [broadinstitute/SignatureAnalyzer-GPU#7]
We have issue to install the package. It seems like because of torch version issue. We get the message as below:

-------------------
Could not find a version that satisfies the requirement torch==1.0.0a0+3c7b575   (from -r SignatureAnalyzer-GPU/requirements-py3.txt (line 7)) (from versions: 0                                                                                                                                                             .1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2)
No matching distribution found for torch==1.0.0a0+3c7b575 (from -r SignatureAnalyzer-GPU/requirements-py3.txt (line 7))
------------------------
Where could we download the specific torch version, torch 1.0.0a0+3c7b575?

Best

**Comment by amarotaylor** [comment]
Hey sorry about that to install torch you should use conda for example:

conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

check out https://pytorch.org/ for more details i.e. cuda versions etc.
