### ISSUE TITLE
How to generate counts matrix?

### ISSUE THREAD

**Issue by jadeshi** [broadinstitute/SignatureAnalyzer-GPU#8]
Hi,
Not an issue with the code itself, but I was wondering how you went about generating your counts matrix input, and if it was straightforward to do so. I'm currently working with a set of known cell lines documented on databases like COMSIC and CCLE that I'd like to featurize using mutational signatures, but I am unsure of how to generate the counts matrix input.

Thanks!

**Comment by amarotaylor** [comment]
Hey,

There is a thorough write up here:

https://www.bioconductor.org/packages/devel/bioc/vignettes/MutationalPatterns/inst/doc/Introduction_to_MutationalPatterns.pdf

However to summarize succinctly: 
1) Call SSNVs and (if you want to include them in your signatures)  Indels 
2) For each sample tabulate the context and base change using either trimers or 5-mers depending on your desired resolution. You can get this context using a variety of tools (Oncotator for example) or by accessing an indexed fasta file. 
3) Collapse categories based on base symmetry i.e. an A->G mutation is the same as T->C
4) Your matrix is just the collection of these counts. 

Hope that helps.
